runtime: python312
env: standard
entrypoint: gunicorn -b :$PORT marmut_15.wsgi:application

handlers:
- url: /static
  static_dir: staticfiles/
- url: /media
  static_dir: mediafiles/
- url: /.*
  script: auto

runtime_config:
  python_version: 3

env_variables:
  # # This setting is used in settings.py to configure your ALLOWED_HOSTS
  # APPENGINE_URL: marmut-kelompok-15.uc.r.appspot.com
  PG_NAME: "kelompok-15"
  PG_USER: "kelompok-15"
  PG_PASSWORD: "iY87FAqeUtLN"
  PG_HOST: "ep-bold-dawn-a2xxvpwo.eu-central-1.pg.koyeb.app"
  PG_PORT: 5432
  JWT_KEY: "a466d1bf421be5ab187eb815b4573ddb85f375f365f233459ba322a79746bdfa"